### ISSUE TITLE
Format Exception

### ISSUE THREAD

**Issue by edwardvuong** [unitedideasco/system_windows#3]
Running the example app on macOS 12.2.1, Apple M1 chip and results in this error when making the call `await systemWindows.getActiveApps()`

```
Unhandled Exception: FormatException: Invalid character (at character 157)
...lLRsUtGE2uj+ZbNt3CyTbLRBkMns3Z1pJjPj\/KRpKT4UQRDBqOCT4P9bwSchaqvtiy2itFC...
                                       ^

#0      _Base64Decoder.decodeChunk (dart:convert/base64.dart:705:7)
#1      _Base64Decoder.decode (dart:convert/base64.dart:629:14)
#2      Base64Decoder.convert (dart:convert/base64.dart:509:26)
#3      new SystemWindow.fromJson (package:system_windows/src/system_window.dart:35:29)
#4      SystemWindows.getActiveApps.<anonymous closure> (package:system_windows/src/system_windows.dart:43:42)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
#9      new List.of (dart:core-patch/array_patch.dart:51:28)
#10     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#11     SystemWindows.getActiveApps (package:system_windows/src/system_windows.dart:44:10)
<asynchronous suspension>
#12     _MyAppState._init.<anonymous closure> (package:system_windows_example/main.dart:33:26)
<asynchronous suspension>

```

**Comment by jakub-stefaniak** [comment]
Thank you for creating this issue. I am aware of this encoding problem. I will fix this soon

**Comment by Roman-Dzerkal** [comment]
Are there some news?
